Repository PraktikumSeoulDevTeam/castleofghosts, pull requests merged in 2020-12, with the labels that each got.

#32 feature/spinner-on-auth
  app/src/App.tsx
  app/src/components/Spinner/Spinner.scss
  app/src/components/Spinner/Spinner.tsx
  app/src/store/User/sagas.ts
  app/src/store/Utility/actions.ts
  app/src/store/Utility/reducer.ts
  app/src/store/Utility/types.ts
  app/src/store/rootReducer.ts
  app/src/store/types.ts
Labels: enhancement

#37 Добавлено св-во autoСomplete в поля ввода
  app/src/components/FormControl/FormControl.tsx
  app/src/components/FormControl/types.ts
  app/src/components/UserDataChange/UserDataChange.tsx
  app/src/components/UserPasswordChange/UserPasswordChange.tsx
  app/src/pages/AuthorizationPage/AuthorizationPage.tsx
  app/src/pages/RegistrationPage/RegistrationPage.tsx
Labels: bug, enhancement

#27 Удален компонент AuthButton
  app/src/components/AuthButton/AuthButton.tsx
  app/src/components/AuthButton/types.ts
  app/src/components/index.ts
Labels: enhancement

#41 Update index.ts
  app/src/api/index.ts
Labels: bug

#39 Feature/feature update user saga
  app/src/components/FormControl/FormControl.tsx
  app/src/components/UserAvatarChange/UserAvatarChange.tsx
  app/src/components/UserDataChange/UserDataChange.tsx
  app/src/components/UserPasswordChange/UserPasswordChange.tsx
  app/src/store/User/actions.ts
  app/src/store/User/reducer.ts
  app/src/store/User/sagas.ts
  app/src/store/User/types.ts
Labels: enhancement

#38 Feature/50 game model
  .eslintrc.json
  app/src/assets/img/char.png
  app/src/assets/img/dima.png
  app/src/assets/img/floor.png
  app/src/assets/img/jenya.png
  app/src/assets/img/nikita.png
  app/src/assets/img/tema.png
  app/src/assets/img/wall.png
  app/src/assets/index.ts
  app/src/assets/scss/_variables.scss
  app/src/canvas/main.ts
  app/src/components/Copyright/Copyright.scss
  app/src/components/Copyright/Copyright.tsx
  app/src/core/bg.canvas.ts
  app/src/core/main.canvas.ts
  app/src/core/sprites/character.ts
  app/src/core/sprites/floor.ts
  app/src/core/sprites/utils.ts
  app/src/core/sprites/wall.ts
  app/src/core/types.ts
  app/src/index.tsx
  app/src/pages/GamePage/GamePage.tsx
  app/webpack.config.js
Labels: enhancement

#40 feature/toast
  app/src/App.tsx
  app/src/assets/scss/init.scss
  app/src/assets/scss/mixins/_typo.scss
  app/src/components/Toaster/Toaster.scss
  app/src/components/Toaster/Toaster.tsx
  app/src/components/index.ts
  app/src/store/Toaster/actions.ts
  app/src/store/Toaster/reducer.ts
  app/src/store/Toaster/sagas.ts
  app/src/store/Toaster/types.ts
  app/src/store/User/sagas.ts
  app/src/store/rootReducer.ts
  app/src/store/rootSaga.ts
  app/src/store/types.ts
Labels: enhancement

#44 Update EditPage.tsx
  app/src/pages/EditPage/EditPage.tsx
Labels: bug

#48 Вариант StartPage.tsx
  app/src/pages/StartPage/StartPage.tsx
Labels: question

#46 Update tsconfig.common.json
  tsconfig.common.json
Labels: bug

#45 Добавлены ограничения в настройки engine и .nvmrc
  .npmrc
  .nvmrc
  README.md
  package.json
Labels: enhancement

#49 Update Toaster.tsx
  app/src/components/Toaster/Toaster.tsx
Labels: bug

#43 Прогресс игрового процесса
  app/src/api/types.ts
  app/src/assets/scss/buttonBar.scss
  app/src/components/Menu/Menu.tsx
  app/src/core/engine.ts
  app/src/core/main.canvas.ts
  app/src/core/types.ts
  app/src/pages/GamePage/GamePage.tsx
  app/src/pages/GamePage/GameUi/GameUi.scss
  app/src/pages/GamePage/GameUi/GameUi.tsx
  app/src/pages/LeaderboardPage/LeaderboardRecord/types.ts
  app/src/store/Game/actions.ts
  app/src/store/Game/reducer.ts
  app/src/store/Game/sagas.ts
  app/src/store/Game/types.ts
  app/src/store/Leaderboard/actions.ts
  app/src/store/Leaderboard/reducer.ts
  app/src/store/Leaderboard/types.ts
  app/src/store/User/reducer.ts
  app/src/store/Utility/reducer.ts
  app/src/store/index.ts
  app/src/store/rootSaga.ts
Labels: enhancement

#47 Обнуление состояние игры
  app/src/pages/GamePage/GamePage.tsx
Labels: enhancement

#42 Feature/feature game start page
  .eslintrc.json
  app/src/assets/scss/init.scss
  app/src/assets/scss/mixins/_typo.scss
  app/src/components/Button/Button.scss
  app/src/components/Copyright/Copyright.scss
  app/src/components/Countdown/Countdown.scss
  app/src/components/Countdown/Countdown.tsx
  app/src/components/Countdown/types.ts
  app/src/components/FormControl/FormControl.scss
  app/src/components/Menu/Menu.tsx
  app/src/components/Spinner/Spinner.tsx
  app/src/components/UserAvatarChange/UserAvatarChange.tsx
  app/src/components/UserDataChange/UserDataChange.tsx
  app/src/components/UserPasswordChange/UserPasswordChange.tsx
  app/src/components/index.ts
  app/src/layouts/UiLayout/UiLayout.scss
  app/src/pages/AuthorizationPage/AuthorizationPage.tsx
  app/src/pages/EditPage/EditPage.tsx
  app/src/pages/ErrorPage/ErrorPage.tsx
  app/src/pages/GamePage/GamePage.tsx
  app/src/pages/GamePage/GameUi/GameUi.tsx
  app/src/pages/LeaderboardPage/LeaderboardPage.tsx
  app/src/pages/LeaderboardPage/LeaderboardRecord/types.ts
  app/src/pages/RegistrationPage/RegistrationPage.tsx
  app/src/pages/StartPage/StartPage.tsx
  app/src/pages/WelcomePage/WelcomePage.tsx
  app/src/pages/index.ts
  app/src/router/AppRouter/AppRouter.tsx
  app/src/router/PrivateRoute/PrivateRoute.tsx
  app/src/store/Game/actions.ts
  app/src/store/Game/reducer.ts
  app/src/store/Game/types.ts
  app/src/store/Leaderboard/actions.ts
  app/src/store/Leaderboard/sagas.ts
  app/src/store/Leaderboard/types.ts
  app/src/store/User/actions.ts
  app/src/store/User/sagas.ts
  app/src/store/User/types.ts
  app/tsconfig.json
  app/webpack.config.js
  package.json
  yarn.lock
Labels: enhancement

#51 Обновлены некритичные зависимости
  package.json
  yarn.lock
Labels: bug

#50 Исправление типов и оформление кода
  app/src/App.tsx
  app/src/api/index.ts
  app/src/components/Button/Button.tsx
  app/src/components/Copyright/Copyright.tsx
  app/src/components/Countdown/Countdown.tsx
  app/src/components/FormControl/FormControl.tsx
  app/src/components/FormControl/types.ts
  app/src/components/Menu/Menu.tsx
  app/src/components/Spinner/Spinner.tsx
  app/src/components/Toaster/Toaster.tsx
  app/src/components/Toaster/types.ts
  app/src/components/UserAvatarChange/UserAvatarChange.tsx
  app/src/components/UserDataChange/UserDataChange.tsx
  app/src/components/UserPasswordChange/UserPasswordChange.tsx
  app/src/core/bg.canvas.ts
  app/src/core/engine.ts
  app/src/core/main.canvas.ts
  app/src/core/sprites/utils.ts
  app/src/core/types.ts
  app/src/layouts/UiLayout/UiLayout.tsx
  app/src/pages/AuthorizationPage/AuthorizationPage.tsx
  app/src/pages/EditPage/EditPage.tsx
  app/src/pages/GamePage/GamePage.tsx
  app/src/pages/GamePage/GameUi/GameUi.tsx
  app/src/pages/LeaderboardPage/LeaderboardPage.tsx
  app/src/pages/LeaderboardPage/LeaderboardRecord/LeaderboardRecord.tsx
  app/src/pages/RegistrationPage/RegistrationPage.tsx
  app/src/pages/StartPage/StartPage.tsx
  app/src/pages/WelcomePage/WelcomePage.tsx
  app/src/router/AppRouter/AppRouter.tsx
  app/src/router/PrivateRoute/PrivateRoute.tsx
  app/src/store/Game/actions.ts
  app/src/store/Game/reducer.ts
  app/src/store/Game/sagas.ts
  app/src/store/Game/types.ts
  app/src/store/Leaderboard/sagas.ts
Labels: bug

#54 Feature/eslint import order
  .eslintrc.json
  app/src/App.tsx
  app/src/api/index.ts
  app/src/components/Countdown/Countdown.tsx
  app/src/components/FormControl/FormControl.tsx
  app/src/components/Menu/Menu.tsx
  app/src/components/Spinner/Spinner.tsx
  app/src/components/Toaster/Toaster.tsx
  app/src/components/UserAvatarChange/UserAvatarChange.tsx
  app/src/components/UserDataChange/UserDataChange.tsx
  app/src/components/UserPasswordChange/UserPasswordChange.tsx
  app/src/components/index.ts
  app/src/core/bg.canvas.ts
  app/src/core/engine.ts
  app/src/core/main.canvas.ts
  app/src/core/sprites/floor.ts
  app/src/core/sprites/wall.ts
  app/src/index.tsx
  app/src/layouts/UiLayout/UiLayout.tsx
  app/src/pages/AuthorizationPage/AuthorizationPage.tsx
  app/src/pages/EditPage/EditPage.tsx
  app/src/pages/ErrorPage/ErrorPage.tsx
  app/src/pages/GamePage/GamePage.tsx
  app/src/pages/GamePage/GameUi/GameUi.tsx
  app/src/pages/LeaderboardPage/LeaderboardPage.tsx
  app/src/pages/LeaderboardPage/LeaderboardRecord/LeaderboardRecord.tsx
  app/src/pages/RegistrationPage/RegistrationPage.tsx
  app/src/pages/StartPage/StartPage.tsx
  app/src/pages/WelcomePage/WelcomePage.tsx
  app/src/router/AppRouter/AppRouter.tsx
  app/src/router/PrivateRoute/PrivateRoute.tsx
  app/src/store/Game/actions.ts
  app/src/store/Game/reducer.ts
  app/src/store/Game/sagas.ts
  app/src/store/Leaderboard/reducer.ts
  app/src/store/Leaderboard/sagas.ts
  app/src/store/Toaster/reducer.ts
  app/src/store/Toaster/sagas.ts
  app/src/store/User/reducer.ts
  app/src/store/User/sagas.ts
  app/src/store/Utility/reducer.ts
  app/src/store/index.ts
  app/src/store/rootReducer.ts
  app/src/store/rootSaga.ts
  app/src/store/types.ts
  app/webpack.config.js
  server/src/server.ts
Labels: enhancement
