Repository PraktikumSeoulDevTeam/castleofghosts, pull requests merged in 2021-01, with the labels that each got.

#59 Обновление axios для устранения уязвимости
  package.json
  yarn.lock
Labels: bug

#61 Fix engine semver for Heroku
  package.json
  yarn.lock
Labels: bug

#63 Fix engine semver for Heroku
  package.json
  yarn.lock
Labels: bug

#58 Feature/feature 77 geolocation api
  app/src/pages/GamePage/GameUi/GameUi.tsx
  app/src/services/geolocation/geolocation.ts
  app/src/store/User/actions.ts
  app/src/store/User/reducer.ts
  app/src/store/User/sagas.ts
  app/src/store/User/types.ts
  app/src/store/index.ts
Labels: enhancement

#53 Feature/feature 54 character move
  app/src/assets/img/char.png
  app/src/components/Countdown/Countdown.scss
  app/src/core/engine.ts
  app/src/core/main.canvas.ts
  app/src/core/sprites/character/character.ts
  app/src/core/types.ts
  app/src/pages/GamePage/GameUi/GameUi.tsx
  app/src/services/LevelGenerator/__levels.ts
  app/src/store/Game/actions.ts
  app/src/store/Game/reducer.ts
  app/src/store/Game/sagas.ts
  app/src/store/Game/types.ts
  app/src/store/index.ts
  yarn.lock
Labels: enhancement

#66 Удаление карты, не имеющей отношение к генератору
  app/src/services/LevelGenerator/__levels.ts
Labels: bug

#56 feature/full-screen-api
  app/src/pages/GamePage/GamePage.tsx
  app/src/pages/StartPage/StartPage.tsx
  app/src/webApi/fullScreen.ts
  package.json
  yarn.lock
Labels: enhancement

#68 Реализация Web Audio API
  app/src/App.tsx
  app/src/assets/audio/click.ogg
  app/src/assets/audio/loop.ogg
  app/src/assets/audio/loose.wav
  app/src/assets/audio/win.ogg
  app/src/assets/index.ts
  app/src/components/AudioSwitch/AudioSwitch.scss
  app/src/components/AudioSwitch/AudioSwitch.tsx
  app/src/components/Button/Button.tsx
  app/src/components/index.ts
  app/src/core/audio/click.ts
  app/src/core/audio/gameLoop.ts
  app/src/core/audio/index.ts
  app/src/core/audio/loose.ts
  app/src/core/audio/types.ts
  app/src/core/audio/utils.ts
  app/src/core/audio/win.ts
  app/src/store/Audio/actions.ts
  app/src/store/Audio/reducer.ts
  app/src/store/Audio/sagas.ts
  app/src/store/Audio/types.ts
  app/src/store/Game/sagas.ts
  app/src/store/User/sagas.ts
  app/src/store/Utility/actions.ts
  app/src/store/rootReducer.ts
  app/src/store/rootSaga.ts
  app/src/store/types.ts
  app/webpack.config.js
Labels: enhancement

#69 Загрузка уровней из файла
  .gitignore
  app/levels/07b564e2-ed2f-45de-b823-1608e77d625e.json
  app/levels/6abcec8e-0ab8-4610-80c1-6f553346e961.json
  app/levels/b069e277-f5bb-43ee-a135-c5386a5a234c.json
  app/src/core/bg.canvas.ts
  app/src/core/engine.ts
  app/src/core/levelLoader.ts
  app/src/core/params.ts
  app/src/core/types.ts
  app/src/pages/GamePage/GamePage.tsx
  app/src/pages/GamePage/GameUi/GameUi.scss
  app/src/pages/GamePage/GameUi/GameUi.tsx
  app/src/pages/StartPage/StartPage.tsx
  app/src/services/LevelGenerator/LevelGenerator.ts
  app/src/services/LevelGenerator/__levels.ts
  app/src/store/Game/actions.ts
  app/src/store/Game/reducer.ts
  app/src/store/Game/sagas.ts
  app/src/store/Game/types.ts
  app/src/store/Level/actions.ts
  app/src/store/Level/reducer.ts
  app/src/store/Level/sagas.ts
  app/src/store/Level/types.ts
  app/src/store/index.ts
  app/src/store/rootReducer.ts
  app/src/store/rootSaga.ts
  app/src/store/types.ts
  app/webpack.config.js
  package.json
  scripts/concatLevels.js
  yarn.lock
Labels: enhancement

#67 feature/map-visibility
  app/src/core/bg.canvas.ts
  app/src/core/engine.ts
  app/src/core/main.canvas.ts
  app/src/core/utils.ts
  app/src/store/Game/sagas.ts
Labels: enhancement

#71 Исправление ошибки при остановке аудио ноды
  app/src/core/audio/click.ts
  app/src/core/audio/gameLoop.ts
  app/src/core/audio/loose.ts
  app/src/core/audio/types.ts
  app/src/core/audio/utils.ts
  app/src/core/audio/win.ts
Labels: bug

#72 Исправление ошибок старта уровня
  app/src/core/bg.canvas.ts
  app/src/core/engine.ts
Labels: bug

#70 Feature/feature 89 key
  app/src/core/bg.canvas.ts
  app/src/core/engine.ts
  app/src/core/sprites/object.ts
  app/src/core/types.ts
  app/src/services/LevelGenerator/__levels.ts
Labels: enhancement

#73 feature/win-end-screen
  app/src/core/bg.canvas.ts
  app/src/core/engine.ts
  app/src/core/params.ts
  app/src/pages/GamePage/GameUi/GameUi.tsx
  app/src/services/LevelGenerator/__levels.ts
  app/src/store/Game/actions.ts
  app/src/store/Game/reducer.ts
  app/src/store/Game/sagas.ts
  app/src/store/Game/types.ts
Labels: enhancement

#75 Аутентификация через Yandex OAuth
  app/src/App.tsx
  app/src/api/index.ts
  app/src/api/test.ts
  app/src/api/types.ts
  app/src/assets/img/logo-yandex.png
  app/src/assets/index.ts
  app/src/assets/scss/_variables.scss
  app/src/assets/scss/index.scss
  app/src/assets/scss/logo.scss
  app/src/components/Button/Button.scss
  app/src/components/Init/Init.tsx
  app/src/components/index.ts
  app/src/core/audio/utils.ts
  app/src/pages/AuthorizationPage/AuthorizationPage.tsx
  app/src/store/User/actions.ts
  app/src/store/User/sagas.ts
  app/src/store/User/types.ts
  app/src/store/index.ts
  app/src/utils/index.ts
  app/webpack.config.js
Labels: enhancement

#77 Рефакторинг игры
  app/levels/6abcec8e-0ab8-4610-80c1-6f553346e961.json
  app/src/assets/img/object.png
  app/src/core/bg.canvas.ts
  app/src/core/engine.ts
  app/src/core/main.canvas.ts
  app/src/core/params.ts
  app/src/core/spirit.canvas.ts
  app/src/core/types.ts
  app/src/core/utils.ts
  app/src/pages/GamePage/GamePage.tsx
  app/src/services/LevelGenerator/__levels.ts
  app/src/store/Game/sagas.ts
  app/src/store/index.ts
Labels: bug, enhancement

#74 Отправка результата игры на сервер и подсчет очков
  app/src/api/index.ts
  app/src/api/types.ts
  app/src/core/engine.ts
  app/src/core/params.ts
  app/src/core/types.ts
  app/src/pages/GamePage/GameUi/GameUi.tsx
  app/src/pages/GamePage/GameUi/Timer/Timer.tsx
  app/src/pages/LeaderboardPage/LeaderboardPage.tsx
  app/src/pages/LeaderboardPage/LeaderboardRecord/LeaderboardRecord.tsx
  app/src/store/Game/actions.ts
  app/src/store/Game/reducer.ts
  app/src/store/Game/sagas.ts
  app/src/store/Game/types.ts
  app/src/store/Leaderboard/actions.ts
  app/src/store/Leaderboard/reducer.ts
  app/src/store/Leaderboard/sagas.ts
  app/src/store/Leaderboard/types.ts
Labels: enhancement
